# Generated by Django 4.2.16 on 2024-09-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_contact',
            new_name='email_for_contact',
        ),
    ]
