# Generated by Django 4.2.16 on 2024-10-08 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cave_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cave_owner_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
