# Generated by Django 4.2.16 on 2024-10-03 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cave',
            name='area',
            field=models.FloatField(help_text='Enter valid values (>0 - 3000) with significant\n         decimal digits separated by a period (e.g., 123.45).', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='cave',
            name='cave_name',
            field=models.CharField(help_text='Enter a unique name. Letters, numbers,\n         spaces, hyphens, and underscores are allowed.', max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Cave name can only contain letters,\n                 numbers, spaces, hyphens, and underscores.', regex='^[a-zA-Z0-9\\s_-]+$')]),
        ),
        migrations.AlterField(
            model_name='cave',
            name='depth',
            field=models.FloatField(help_text='Enter valid values (>0 - 500) with significant\n         decimal digits separated by a period (e.g., 123.45).', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='cave',
            name='elevation',
            field=models.IntegerField(help_text='Enter values between 0 and 3000 with\n         no significant decimal digits.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='cave',
            name='latitude',
            field=models.FloatField(help_text='Please enter the latitude coordinate\n         in the Decimal Degrees format (e.g., -20.102852)', validators=[django.core.validators.RegexValidator(regex='^(?![+-]00\\.000000$)[+-]\\d{2}\\.\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='cave',
            name='length',
            field=models.FloatField(help_text='Enter values between 5 and 3000 with significant\n         decimal digits separated by a period (e.g., 12.34).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='cave',
            name='longitude',
            field=models.FloatField(help_text='Please enter the longitude coordinate\n         in the Decimal Degrees format (e.g., -43.453612)', validators=[django.core.validators.RegexValidator(regex='^(?![+-]00\\.000000$)[+-]\\d{2}\\.\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='cave',
            name='volume',
            field=models.FloatField(help_text='Enter valid values (>0 - 3000) with significant\n         decimal digits separated by a period (e.g., 123.45).', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
