# Generated by Django 4.2.16 on 2024-10-03 20:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caves', '0002_alter_cave_area_alter_cave_cave_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cave',
            name='cave_maps',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='JPG or PDF are supported formats.', max_length=255, verbose_name='cave_maps'),
        ),
        migrations.AlterField(
            model_name='cave',
            name='geomorph_unit',
            field=models.IntegerField(choices=[(0, 'Serra da Serpentina'), (2, 'Itabira'), (3, 'Serra da Piedade'), (4, 'João Monlevade'), (5, 'Quadrilátero Oeste'), (6, 'Serra Azul'), (7, 'Morrarias de Dom Bosco'), (8, 'Serra de Ouro Preto - Antônio Pereira'), (9, 'Escarpa Oriental do Caraça'), (10, 'Serra do Gandarela')], default=0),
        ),
    ]
